[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "nginx"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "php spark serve --host=0.0.0.0 --port=$PORT"
